twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        eve_characters: '@App\EveApi\Repository\CharacterRepository'
        eve_auth: '@App\EveApi\Authentication'
