parameters:
    session_memcached_host: 127.0.0.1
    session_memcached_port: 11211
    session_memcached_prefix: 'evetoolkit:session:'
    session_memcached_expire: 14400

framework:
    session:
        handler_id: session.handler.memcached

services:
    session.memcached:
        class: Memcached
        calls:
            - [ addServer, [ '%session_memcached_host%', '%session_memcached_port%' ]]

    session.handler.memcached:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: ['@session.memcached', { prefix: '%session_memcached_prefix%', expiretime: '%session_memcached_expire%' }]
