monolog:
    handlers:
        # this "file_log" key could be anything
        file_log:
            type: stream
            # log to var/log/(environment).log
            path: "/%kernel.logs_dir%/evetoolkit/%kernel.environment%.log"
            # log *all* messages (debug is lowest level)
            level: debug
